-- ==================================================================
-- 실재고 조사 — 위치별로 돌아보며 전산 재고와 실물이 맞는지 확인하는 감사 세션
--
-- 실행 방법: Supabase 대시보드 → SQL Editor → New query 에 붙여넣고 Run
-- 여러 번 실행해도 안전합니다 (if not exists).
--
-- 세션 하나 = 위치 하나를 조사한 기록. results는 그 세션 시작 시점의 전산 재고 목록을
-- jsonb 배열로 통째로 담습니다(건별 자식 테이블 대신 — 조회/검색이 필요 없고 세션 단위로만
-- 읽고 쓰는 용도라 더 단순함):
--   [{ assetId, category, model, brand, status, scannedAt, note }]
--   status: '미확인' | '확인됨' | '목록외발견'
-- ==================================================================

create table if not exists public.it_stocktake_sessions (
  id            uuid primary key default gen_random_uuid(),
  seq           bigint generated by default as identity,

  location      text not null,
  status        text not null default '진행중' check (status in ('진행중', '완료')),
  started_by    text not null default '',
  results       jsonb not null default '[]'::jsonb,

  started_at    timestamptz not null default now(),
  completed_at  timestamptz,

  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

create index if not exists it_stocktake_sessions_location_idx on public.it_stocktake_sessions (location);

drop trigger if exists it_stocktake_sessions_set_updated_at on public.it_stocktake_sessions;
create trigger it_stocktake_sessions_set_updated_at
  before update on public.it_stocktake_sessions
  for each row execute function public.set_updated_at();

-- 다른 대장들과 동일한 보안 모델: RLS 켜고 정책은 만들지 않음 → service_role 서버 코드만 접근
alter table public.it_stocktake_sessions enable row level security;
